# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'track_controller.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 507)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        self.manual_mode = QtWidgets.QPushButton(self.centralwidget)
        self.manual_mode.setGeometry(QtCore.QRect(80, 50, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.manual_mode.setFont(font)
        self.manual_mode.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.manual_mode.setObjectName("manual_mode")
        # self.manual_mode.clicked.connect(self.set_manual_mode)

        self.browse = QtWidgets.QPushButton(self.centralwidget)
        self.browse.setGeometry(QtCore.QRect(350, 70, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.browse.setFont(font)
        self.browse.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browse.setObjectName("browse")
        self.browse.clicked.connect(self.browse_files)


        self.file_upload = QtWidgets.QLabel(self.centralwidget)
        self.file_upload.setGeometry(QtCore.QRect(350, 30, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.file_upload.setFont(font)
        self.file_upload.setObjectName("file_upload")

        self.filename = QtWidgets.QLabel(self.centralwidget)
        self.filename.setGeometry(QtCore.QRect(310, 130, 181, 20))
        self.filename.setFixedWidth(250)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.filename.setFont(font)
        self.filename.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.filename.setObjectName("filename")

        self.block_number = QtWidgets.QLCDNumber(self.centralwidget)
        self.block_number.setGeometry(QtCore.QRect(350, 270, 151, 111))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.block_number.setFont(font)
        self.block_number.setObjectName("block_number")

        self.occupancy = QtWidgets.QLabel(self.centralwidget)
        self.occupancy.setGeometry(QtCore.QRect(320, 190, 221, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.occupancy.setFont(font)
        self.occupancy.setObjectName("occupancy")

        self.switch_pos = QtWidgets.QLabel(self.centralwidget)
        self.switch_pos.setGeometry(QtCore.QRect(60, 190, 221, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.switch_pos.setFont(font)
        self.switch_pos.setObjectName("switch_pos")

        self.switch_block = QtWidgets.QLabel(self.centralwidget)
        self.switch_block.setGeometry(QtCore.QRect(60, 280, 91, 101))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.switch_block.setFont(font)
        self.switch_block.setObjectName("switch_block")

        self.switch_block_number = QtWidgets.QLCDNumber(self.centralwidget)
        self.switch_block_number.setGeometry(QtCore.QRect(150, 290, 141, 81))
        self.switch_block_number.setObjectName("switch_block_number")

        self.light_block_6 = QtWidgets.QLabel(self.centralwidget)
        self.light_block_6.setGeometry(QtCore.QRect(60, 390, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.light_block_6.setFont(font)
        self.light_block_6.setObjectName("light_block_6")

        self.light_block_7 = QtWidgets.QLabel(self.centralwidget)
        self.light_block_7.setGeometry(QtCore.QRect(60, 430, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.light_block_7.setFont(font)
        self.light_block_7.setObjectName("light_block_7")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 400, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 587, 21))
        self.menubar.setObjectName("menubar")
        self.menuTrack_Controller_UI = QtWidgets.QMenu(self.menubar)
        self.menuTrack_Controller_UI.setObjectName("menuTrack_Controller_UI")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuTrack_Controller_UI.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.manual_mode.setText(_translate("MainWindow", "Manual Mode"))
        self.browse.setText(_translate("MainWindow", "Browse"))
        self.file_upload.setText(_translate("MainWindow", "File Upload"))
        self.filename.setText(_translate("MainWindow", "Filename"))
        self.occupancy.setText(_translate("MainWindow", "Occupied Block"))
        self.switch_pos.setText(_translate("MainWindow", "Switch Position"))
        self.switch_block.setText(_translate("MainWindow", "Block:"))
        self.light_block_6.setText(_translate("MainWindow", "Light @ Block 6:"))
        self.light_block_7.setText(_translate("MainWindow", "Light @ Block 11: "))
        self.label.setText(_translate("MainWindow", "RR Crossing:"))
        self.menuTrack_Controller_UI.setTitle(_translate("MainWindow", "Track Controller UI"))



    def browse_files(self):
        fname = QtWidgets.QFileDialog.getOpenFileName(self, 'Open PLC File', 'C:/Users/lucas')
        self.filename.setText(fname[0])

    # # TODO - configure this to open the manual mode dialogue
    # def set_manual_mode(self):
    #
    #
    # # TODO - update the LCD object with current occupied block #
    # # def update_occupancy(self):
    #
    #
    # # TODO - update the LCD object with current switch position (block number)
    # def update_switch_position(self):
    #
    #
    # # TODO - update the light state based on the light number
    # def update_light_state(self, light_number):
    #
    #
    # # TODO - update the railroad crossing status based on block occupancy
    # def update_RR_crossing(self):

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())